import { WindowData } from "./types";

export const data: WindowData[] = [
  {
      "alwaysOnTop": false,
      "focused": true,
      "height": 944,
      "id": 1388900961,
      "incognito": false,
      "left": 0,
      "state": "maximized",
      "tabs": [
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": 1593186407,
              "height": 857,
              "highlighted": false,
              "id": 1388904011,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "javascript - Change how fast \"title\" attribute's tooltip appears - Stack Overflow",
              "url": "https://stackoverflow.com/questions/9150796/change-how-fast-title-attributes-tooltip-appears",
              "width": 1117,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://developer.mozilla.org/favicon-48x48.cbbd161b.png",
              "groupId": 1593186407,
              "height": 0,
              "highlighted": false,
              "id": 1388904645,
              "incognito": false,
              "index": 1,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "cursor - CSS: Cascading Style Sheets | MDN",
              "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/cursor",
              "width": 0,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://www.overleaf.com/favicon.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388904518,
              "incognito": false,
              "index": 2,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Payment Data - Descriptive - Online LaTeX Editor Overleaf",
              "url": "https://www.overleaf.com/project/65806a19681ba1158b81219d",
              "width": 2165,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://v0.dev/icon-19iptc.svg?94ebf4f1268986e0",
              "groupId": 765941577,
              "height": 1328,
              "highlighted": false,
              "id": 1388905057,
              "incognito": false,
              "index": 3,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "chrome extension sidepanel that manages tabs and tabgroups. there should be a search box on top. | A v0.dev template - v0",
              "url": "https://v0.dev/r/SV7jEuxI2jH",
              "width": 2560,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://www.google.com/favicon.ico",
              "groupId": 765941577,
              "height": 0,
              "highlighted": false,
              "id": 1388905985,
              "incognito": false,
              "index": 4,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "chrome ui library react - Google Search",
              "url": "https://www.google.com/search?sca_esv=600688552&rlz=1C5CHFA_enTH982TH982&sxsrf=ACQVn0_-OQinhqcD7fiUnxUxrIy3dEFdHw:1705999838195&q=chrome+ui+library+react&tbm=isch&source=lnms&sa=X&ved=2ahUKEwj3mt7SkPODAxWObWwGHc0NDCYQ0pQJegQIDBAB&biw=2165&bih=1328&dpr=1",
              "width": 0,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906007,
              "incognito": false,
              "index": 5,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Extensions",
              "url": "chrome://extensions/",
              "width": 0,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://developer.mozilla.org/favicon-48x48.cbbd161b.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905692,
              "incognito": false,
              "index": 6,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Subsequent-sibling combinator - CSS: Cascading Style Sheets | MDN",
              "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/Subsequent-sibling_combinator",
              "width": 2560,
              "windowId": 1388900961
          },
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://statics.teams.cdn.office.net/hashed/favicon/prod/favicon-f1722d9.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388905702,
              "incognito": false,
              "index": 7,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "Taskforce Digital World | Microsoft Teams classic",
              "url": "https://teams.microsoft.com/_#/conversations/19:fe411f97a7544ad79985e40a938b1bf1@thread.v2?ctx=chat",
              "width": 1117,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://res.cdn.office.net/owamail/20240112004.09/resources/images/favicons/mail-seen.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388905744,
              "incognito": false,
              "index": 8,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Mail - Thiti Tosborvorn (ฐิติ ทศบวร) - Outlook",
              "url": "https://outlook.office.com/mail/id/AAQkAGVhMzE3ZmQwLWI2ZWItNDczNi1hYjI1LTU3NGM1ZWQ5ZmFkYwAQABAOy8BpfE3vjt6oICZZjXw%3D",
              "width": 1512,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://docs.oracle.com/sp_common/rest-template/ohc-common/img/favicon.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388905992,
              "incognito": false,
              "index": 9,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "REST API for Oracle Fusion Cloud HCM - About the REST APIs",
              "url": "https://docs.oracle.com/en/cloud/saas/human-resources/24a/farws/index.html",
              "width": 1512,
              "windowId": 1388900961
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://static.xx.fbcdn.net/rsrc.php/yT/r/aGT3gskzWBf.ico?_nc_eui2=AeH9-IE5KegLCmFHjlEXVNddrSiY817De8atKJjzXsN7xk790IvzeHZsXFDamY9z0_E",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388906089,
              "incognito": false,
              "index": 10,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Facebook",
              "url": "https://www.facebook.com/",
              "width": 1512,
              "windowId": 1388900961
          }
      ],
      "top": 38,
      "type": "normal",
      "width": 1512,
      "kind": "window",
      "children": [
          {
              "collapsed": false,
              "color": "grey",
              "id": 1593186407,
              "title": "Web Development",
              "windowId": 1388900961,
              "kind": "tabGroup",
              "children": [
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
                      "groupId": 1593186407,
                      "height": 857,
                      "highlighted": false,
                      "id": 1388904011,
                      "incognito": false,
                      "index": 0,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "javascript - Change how fast \"title\" attribute's tooltip appears - Stack Overflow",
                      "url": "https://stackoverflow.com/questions/9150796/change-how-fast-title-attributes-tooltip-appears",
                      "width": 1117,
                      "windowId": 1388900961,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": true,
                      "favIconUrl": "https://developer.mozilla.org/favicon-48x48.cbbd161b.png",
                      "groupId": 1593186407,
                      "height": 0,
                      "highlighted": false,
                      "id": 1388904645,
                      "incognito": false,
                      "index": 1,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "unloaded",
                      "title": "cursor - CSS: Cascading Style Sheets | MDN",
                      "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/cursor",
                      "width": 0,
                      "windowId": 1388900961,
                      "kind": "tab",
                      "children": []
                  }
              ]
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://www.overleaf.com/favicon.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388904518,
              "incognito": false,
              "index": 2,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Payment Data - Descriptive - Online LaTeX Editor Overleaf",
              "url": "https://www.overleaf.com/project/65806a19681ba1158b81219d",
              "width": 2165,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          },
          {
              "collapsed": false,
              "color": "blue",
              "id": 765941577,
              "title": "",
              "windowId": 1388900961,
              "kind": "tabGroup",
              "children": [
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://v0.dev/icon-19iptc.svg?94ebf4f1268986e0",
                      "groupId": 765941577,
                      "height": 1328,
                      "highlighted": false,
                      "id": 1388905057,
                      "incognito": false,
                      "index": 3,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "chrome extension sidepanel that manages tabs and tabgroups. there should be a search box on top. | A v0.dev template - v0",
                      "url": "https://v0.dev/r/SV7jEuxI2jH",
                      "width": 2560,
                      "windowId": 1388900961,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": true,
                      "favIconUrl": "https://www.google.com/favicon.ico",
                      "groupId": 765941577,
                      "height": 0,
                      "highlighted": false,
                      "id": 1388905985,
                      "incognito": false,
                      "index": 4,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "unloaded",
                      "title": "chrome ui library react - Google Search",
                      "url": "https://www.google.com/search?sca_esv=600688552&rlz=1C5CHFA_enTH982TH982&sxsrf=ACQVn0_-OQinhqcD7fiUnxUxrIy3dEFdHw:1705999838195&q=chrome+ui+library+react&tbm=isch&source=lnms&sa=X&ved=2ahUKEwj3mt7SkPODAxWObWwGHc0NDCYQ0pQJegQIDBAB&biw=2165&bih=1328&dpr=1",
                      "width": 0,
                      "windowId": 1388900961,
                      "kind": "tab",
                      "children": []
                  }
              ]
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906007,
              "incognito": false,
              "index": 5,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Extensions",
              "url": "chrome://extensions/",
              "width": 0,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://developer.mozilla.org/favicon-48x48.cbbd161b.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905692,
              "incognito": false,
              "index": 6,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Subsequent-sibling combinator - CSS: Cascading Style Sheets | MDN",
              "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/Subsequent-sibling_combinator",
              "width": 2560,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          },
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://statics.teams.cdn.office.net/hashed/favicon/prod/favicon-f1722d9.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388905702,
              "incognito": false,
              "index": 7,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "Taskforce Digital World | Microsoft Teams classic",
              "url": "https://teams.microsoft.com/_#/conversations/19:fe411f97a7544ad79985e40a938b1bf1@thread.v2?ctx=chat",
              "width": 1117,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://res.cdn.office.net/owamail/20240112004.09/resources/images/favicons/mail-seen.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388905744,
              "incognito": false,
              "index": 8,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Mail - Thiti Tosborvorn (ฐิติ ทศบวร) - Outlook",
              "url": "https://outlook.office.com/mail/id/AAQkAGVhMzE3ZmQwLWI2ZWItNDczNi1hYjI1LTU3NGM1ZWQ5ZmFkYwAQABAOy8BpfE3vjt6oICZZjXw%3D",
              "width": 1512,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://docs.oracle.com/sp_common/rest-template/ohc-common/img/favicon.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388905992,
              "incognito": false,
              "index": 9,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "REST API for Oracle Fusion Cloud HCM - About the REST APIs",
              "url": "https://docs.oracle.com/en/cloud/saas/human-resources/24a/farws/index.html",
              "width": 1512,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://static.xx.fbcdn.net/rsrc.php/yT/r/aGT3gskzWBf.ico?_nc_eui2=AeH9-IE5KegLCmFHjlEXVNddrSiY817De8atKJjzXsN7xk790IvzeHZsXFDamY9z0_E",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388906089,
              "incognito": false,
              "index": 10,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Facebook",
              "url": "https://www.facebook.com/",
              "width": 1512,
              "windowId": 1388900961,
              "kind": "tab",
              "children": []
          }
      ]
  },
  {
      "alwaysOnTop": false,
      "focused": false,
      "height": 944,
      "id": 1388902663,
      "incognito": false,
      "left": 0,
      "state": "maximized",
      "tabs": [
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "http://localhost:5173/vite.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906081,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Vite + React",
              "url": "http://localhost:5173/",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://www.google.com/favicon.ico",
              "groupId": 738097822,
              "height": 0,
              "highlighted": false,
              "id": 1388905989,
              "incognito": false,
              "index": 1,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "react component label click rename - Google Search",
              "url": "https://www.google.com/search?q=react+component+label+click+rename&rlz=1C5CHFA_enTH982TH982&oq=react+component+label+click+rename&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigAdIBCDg1NDVqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": 738097822,
              "height": 1328,
              "highlighted": false,
              "id": 1388905407,
              "incognito": false,
              "index": 2,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Shaddix/dnd-kit-sortable-tree at ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
              "url": "https://github.com/Shaddix/dnd-kit-sortable-tree/tree/ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://statics.teams.cdn.office.net/evergreen-assets/icons/microsoft_teams_logo_refresh.ico",
              "groupId": 669358666,
              "height": 857,
              "highlighted": false,
              "id": 1388904938,
              "incognito": false,
              "index": 3,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Chat | Payment data | Microsoft Teams",
              "url": "https://teams.microsoft.com/v2/?meetingjoin=true",
              "width": 1512,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905148,
              "incognito": false,
              "index": 4,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "ChatGPT - DALL·E",
              "url": "https://chat.openai.com/g/g-2fkFE8rbu-dall-e/c/d26e1592-1340-4d3a-920b-a97fdeee38d2",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906052,
              "incognito": false,
              "index": 5,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "clauderic/dnd-kit: The modern, lightweight, performant, accessible and extensible drag & drop toolkit for React.",
              "url": "https://github.com/clauderic/dnd-kit?tab=readme-ov-file",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906055,
              "incognito": false,
              "index": 6,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "dnd-kit/playground at master · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/tree/master/playground",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905903,
              "incognito": false,
              "index": 7,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "dnd-kit/stories/components at master · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/tree/master/stories/components",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/favicon.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905879,
              "incognito": false,
              "index": 8,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Examples / Tree / Sortable - Collapsible ⋅ Storybook",
              "url": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-tree-sortable--collapsible",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906014,
              "incognito": false,
              "index": 9,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Sortable - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/presets/sortable",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://playcode.io/static/img/favicons/favicon@2x.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905824,
              "incognito": false,
              "index": 10,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "1032571 - PlayCode",
              "url": "https://playcode.io/1032571",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905713,
              "incognito": false,
              "index": 11,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Drag Overlay - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/api-documentation/draggable/drag-overlay",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/favicon.ico",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906058,
              "incognito": false,
              "index": 12,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Examples / Form Elements / Switch - Basic Setup ⋅ Storybook",
              "url": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-form-elements-switch--basic-setup",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906072,
              "incognito": false,
              "index": 13,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Download GitHub directory",
              "url": "https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fclauderic%2Fdnd-kit%2Ftree%2Fmaster%2Fstories%2Fcomponents",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://www.google.com/favicon.ico",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906075,
              "incognito": false,
              "index": 14,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "vite \"css modules\" site:stackoverflow.com - Google Search",
              "url": "https://www.google.com/search?q=vite+%22css+modules%22+site%3Astackoverflow.com&sca_esv=601029419&rlz=1C5CHFA_enTH982TH982&biw=2560&bih=1328&sxsrf=ACQVn0_ZbL4e6Ovx-4ddTVxGG84SnFOKkA%3A1706088294296&ei=ZtewZbPYEdKfseMPw8KT2As&ved=0ahUKEwizo_KV2vWDAxXST2wGHUPhBLsQ4dUDCBA&uact=5&oq=vite+%22css+modules%22+site%3Astackoverflow.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiKXZpdGUgImNzcyBtb2R1bGVzIiBzaXRlOnN0YWNrb3ZlcmZsb3cuY29tSI0XUOYHWIIVcAF4AJABAJgBS6ABkwGqAQEyuAEDyAEA-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp#ip=1",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906078,
              "incognito": false,
              "index": 15,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Vite + Sass + CSS Modules: `composes` prop limitation - Stack Overflow",
              "url": "https://stackoverflow.com/questions/75243712/vite-sass-css-modules-composes-prop-limitation",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905941,
              "incognito": false,
              "index": 16,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "reactjs - Scope CSS with React + Vite - Stack Overflow",
              "url": "https://stackoverflow.com/questions/77061660/scope-css-with-react-vite",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://vitejs.dev/logo.svg",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905944,
              "incognito": false,
              "index": 17,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Shared Options | Vite",
              "url": "https://vitejs.dev/config/shared-options.html#css-modules",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://www.bot.or.th/etc.clientlibs/bot/clientlibs/clientlib-site/resources/images/shortcut.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905954,
              "incognito": false,
              "index": 18,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Daily Foreign Exchange Rates",
              "url": "https://www.bot.or.th/en/statistics/exchange-rate.html",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388905957,
              "incognito": false,
              "index": 19,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "reactjs - How to import CSS modules with Typescript, React and Webpack - Stack Overflow",
              "url": "https://stackoverflow.com/questions/41336858/how-to-import-css-modules-with-typescript-react-and-webpack",
              "width": 1512,
              "windowId": 1388902663
          }
      ],
      "top": 38,
      "type": "normal",
      "width": 1512,
      "kind": "window",
      "children": [
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "http://localhost:5173/vite.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906081,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Vite + React",
              "url": "http://localhost:5173/",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "collapsed": false,
              "color": "yellow",
              "id": 738097822,
              "title": "React Component & ESLint Information",
              "windowId": 1388902663,
              "kind": "tabGroup",
              "children": [
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": true,
                      "favIconUrl": "https://www.google.com/favicon.ico",
                      "groupId": 738097822,
                      "height": 0,
                      "highlighted": false,
                      "id": 1388905989,
                      "incognito": false,
                      "index": 1,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "unloaded",
                      "title": "react component label click rename - Google Search",
                      "url": "https://www.google.com/search?q=react+component+label+click+rename&rlz=1C5CHFA_enTH982TH982&oq=react+component+label+click+rename&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigAdIBCDg1NDVqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",
                      "width": 0,
                      "windowId": 1388902663,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                      "groupId": 738097822,
                      "height": 1328,
                      "highlighted": false,
                      "id": 1388905407,
                      "incognito": false,
                      "index": 2,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "Shaddix/dnd-kit-sortable-tree at ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
                      "url": "https://github.com/Shaddix/dnd-kit-sortable-tree/tree/ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
                      "width": 2560,
                      "windowId": 1388902663,
                      "kind": "tab",
                      "children": []
                  }
              ]
          },
          {
              "collapsed": false,
              "color": "red",
              "id": 669358666,
              "title": "Microsoft Learning & Teams",
              "windowId": 1388902663,
              "kind": "tabGroup",
              "children": [
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://statics.teams.cdn.office.net/evergreen-assets/icons/microsoft_teams_logo_refresh.ico",
                      "groupId": 669358666,
                      "height": 857,
                      "highlighted": false,
                      "id": 1388904938,
                      "incognito": false,
                      "index": 3,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "Chat | Payment data | Microsoft Teams",
                      "url": "https://teams.microsoft.com/v2/?meetingjoin=true",
                      "width": 1512,
                      "windowId": 1388902663,
                      "kind": "tab",
                      "children": []
                  }
              ]
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905148,
              "incognito": false,
              "index": 4,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "ChatGPT - DALL·E",
              "url": "https://chat.openai.com/g/g-2fkFE8rbu-dall-e/c/d26e1592-1340-4d3a-920b-a97fdeee38d2",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906052,
              "incognito": false,
              "index": 5,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "clauderic/dnd-kit: The modern, lightweight, performant, accessible and extensible drag & drop toolkit for React.",
              "url": "https://github.com/clauderic/dnd-kit?tab=readme-ov-file",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906055,
              "incognito": false,
              "index": 6,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "dnd-kit/playground at master · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/tree/master/playground",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905903,
              "incognito": false,
              "index": 7,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "dnd-kit/stories/components at master · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/tree/master/stories/components",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/favicon.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905879,
              "incognito": false,
              "index": 8,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Examples / Tree / Sortable - Collapsible ⋅ Storybook",
              "url": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-tree-sortable--collapsible",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906014,
              "incognito": false,
              "index": 9,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Sortable - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/presets/sortable",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://playcode.io/static/img/favicons/favicon@2x.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905824,
              "incognito": false,
              "index": 10,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "1032571 - PlayCode",
              "url": "https://playcode.io/1032571",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905713,
              "incognito": false,
              "index": 11,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Drag Overlay - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/api-documentation/draggable/drag-overlay",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/favicon.ico",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906058,
              "incognito": false,
              "index": 12,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Examples / Form Elements / Switch - Basic Setup ⋅ Storybook",
              "url": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-form-elements-switch--basic-setup",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906072,
              "incognito": false,
              "index": 13,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Download GitHub directory",
              "url": "https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fclauderic%2Fdnd-kit%2Ftree%2Fmaster%2Fstories%2Fcomponents",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://www.google.com/favicon.ico",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906075,
              "incognito": false,
              "index": 14,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "vite \"css modules\" site:stackoverflow.com - Google Search",
              "url": "https://www.google.com/search?q=vite+%22css+modules%22+site%3Astackoverflow.com&sca_esv=601029419&rlz=1C5CHFA_enTH982TH982&biw=2560&bih=1328&sxsrf=ACQVn0_ZbL4e6Ovx-4ddTVxGG84SnFOKkA%3A1706088294296&ei=ZtewZbPYEdKfseMPw8KT2As&ved=0ahUKEwizo_KV2vWDAxXST2wGHUPhBLsQ4dUDCBA&uact=5&oq=vite+%22css+modules%22+site%3Astackoverflow.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiKXZpdGUgImNzcyBtb2R1bGVzIiBzaXRlOnN0YWNrb3ZlcmZsb3cuY29tSI0XUOYHWIIVcAF4AJABAJgBS6ABkwGqAQEyuAEDyAEA-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp#ip=1",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388906078,
              "incognito": false,
              "index": 15,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Vite + Sass + CSS Modules: `composes` prop limitation - Stack Overflow",
              "url": "https://stackoverflow.com/questions/75243712/vite-sass-css-modules-composes-prop-limitation",
              "width": 0,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905941,
              "incognito": false,
              "index": 16,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "reactjs - Scope CSS with React + Vite - Stack Overflow",
              "url": "https://stackoverflow.com/questions/77061660/scope-css-with-react-vite",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://vitejs.dev/logo.svg",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905944,
              "incognito": false,
              "index": 17,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Shared Options | Vite",
              "url": "https://vitejs.dev/config/shared-options.html#css-modules",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://www.bot.or.th/etc.clientlibs/bot/clientlibs/clientlib-site/resources/images/shortcut.png",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388905954,
              "incognito": false,
              "index": 18,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Daily Foreign Exchange Rates",
              "url": "https://www.bot.or.th/en/statistics/exchange-rate.html",
              "width": 2560,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388905957,
              "incognito": false,
              "index": 19,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "reactjs - How to import CSS modules with Typescript, React and Webpack - Stack Overflow",
              "url": "https://stackoverflow.com/questions/41336858/how-to-import-css-modules-with-typescript-react-and-webpack",
              "width": 1512,
              "windowId": 1388902663,
              "kind": "tab",
              "children": []
          }
      ]
  }
]